config/routes.rb
Rails.application.routes.draw do
  resources :artists, :books, :video_games, :movies, :reviews, :users, :sessions
  resources :likes, only: [:new, :create, :destroy]

  root to: 'pages#home', as: 'homepage'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  include Reviewables::InstanceMethods
  extend Reviewables::ClassMethods
  has_many :reviews, as: :reviewable
  validates :title, presence: true, uniqueness: true

end

app/models/book.rb
class Book < ApplicationRecord
  include Reviewables::InstanceMethods
  extend Reviewables::ClassMethods
  has_many :reviews, as: :reviewable
  has_many :likes, as: :likeable
  validates :title, presence: true, uniqueness: true
  validates :author, presence: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
  # validates :content, :rating, presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  include Reviewables::InstanceMethods
  extend Reviewables::ClassMethods
  has_many :reviews, as: :reviewable
  validates :title, presence: true, uniqueness: true
  validates :director, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :reviewable, polymorphic: true
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, less_than_or_equal_to: 5, greater_than_or_equal_to: 1 }
  validates :user_id, uniqueness: { scope: :reviewable, message: "You can only write one review" }
end

app/models/reviewables.rb
module Reviewables

  module InstanceMethods

    def average_rating
      if !reviews.empty?
        ratings = reviews.collect { |review| review.rating }
        (ratings.inject{ |sum, el| sum + el }.to_f / ratings.size).round(2)
      else
        "No reviews"
      end
    end

  end

  module ClassMethods

    def top_5
      array = self.all.collect do |instance|
        unless instance.average_rating == "No reviews"
          instance
        end
      end.compact

      array = array.sort_by do |instance|
        instance.average_rating
      end
      array.pop(5).reverse!
    end

  end



end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :reviewables, through: :reviews
  
  has_many :likes
  has_many :likeables, through: :likes
  has_secure_password

  validates :name, :email, :password_digest, :username, presence: true
  validates :email, :username, uniqueness: true
end

app/models/video_game.rb
class VideoGame < ApplicationRecord
  include Reviewables::InstanceMethods
  extend Reviewables::ClassMethods
  has_many :reviews, as: :reviewable
  validates :title, presence: true, uniqueness: true

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])

    if logged_in?
      @review = Review.find_or_initialize_by(reviewable_id: @artist.id, user_id: current_user.id, reviewable_type: "Artist")
    else
      @review = Review.find_by(reviewable_id: @artist.id, reviewable_type: "Artist")
    end

    if logged_in?
      @like = Like.find_or_initialize_by(likeable_id: @artist.id, user_id: current_user.id, likeable_type: "Artist")
    end
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    unless @artist.save
      render :new
    else
      flash[:notice] = "Artist has been successfully created"
      redirect_to artist_path(@artist)
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.update(artist_params)
    redirect_to artist_path(@artist)
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:title)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])

    if logged_in?
      @review = Review.find_or_initialize_by(reviewable_id: @book.id, user_id: current_user.id, reviewable_type: "Book")
    else
      @review = Review.find_by(reviewable_id: @book.id, reviewable_type: "Book")
    end

    if logged_in?
      @like = Like.find_or_initialize_by(likeable_id: @book.id, user_id: current_user.id, likeable_type: "Book")
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    unless @book.save
      render :new
    else
      flash[:notice] = "Book has been successfully created"
      redirect_to book_path(@book)
    end
  end
  private
  def book_params
    params.require(:book).permit(:title, :author)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def new
  end

  def create
    @like = Like.new(like_params)
    @like.user_id = current_user.id
    @like.save
    flash[:notice] = "Successfully added to your list!"
    redirect_to "/#{@like.likeable_type.underscore.pluralize}/#{@like.likeable_id}"
  end

  def destroy
    @like = Like.find(params[:id])
    path = "/#{@like.likeable_type.underscore.pluralize}/#{@like.likeable_id}"
    @like.destroy
    flash[:notice] = "Successfully removed from your list!"
    redirect_to path
  end

  private
  def like_params
    params.require(:like).permit(:likeable_type, :likeable_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password_confirmation, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_games_helper.rb
module VideoGamesHelper
end

app/views/artists/edit.html.erb
<%= form_for(@artist) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/artists/index.html.erb
<div class="container">

  <figure class="center">
    <%= image_tag('LISTED-MUSIC-LOGO.png')%>
  </figure>


  <ul class="collection with-header center">
    <li class="collection-header"><h4>Top Artists</h4></li>
    <% @artists.first.class.top_5.collect do |artist| %>
      <li class="collection-item hoverable"><%= link_to artist.title, artist_path(artist) %></li>
    <% end %>
  </ul>

  <div class="row center"><%= link_to "Create New Artist", new_artist_path, class: "btn-large waves-effect waves-light teal lighten-1" %></div>

  <h4 class="center">All Artists</h4>
  <ul>
    <% @artists.each do |artist| %>
      <li class="center"><%= link_to artist.title, artist_path(artist) %></li>
    <% end %>
  </ul>


</div>

app/views/artists/new.html.erb
<h1>Create a New Artist</h1>

<% @artist.errors.full_messages.each do |msg| %>
<p><%= msg %></p>
<% end %>

<%= form_for(@artist) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<div class="center reviewable-head z-depth-1">
  <h2><%= @artist.title %></h2>
  
  <% if @review %>
    <label class="tiny">Average Rating: </label><span><%= @review.reviewable.average_rating %></span>
  <% end %>

  <% if logged_in? %>
    <%= render 'partials/like_form' %>
  <% end %>
</div>


<div class="container reviewable-content">
  <div class="row">
    <div class="col s6">
      <%= render 'partials/review_list' %>
    </div>
    <div class="col s5 right">
      <% if logged_in? %>
        <%= render 'partials/review_form' %>
      <% else %>
        <%= render 'partials/login_signup' %>
      <% end %>
    </div>
  </div>

</div>