config/routes.rb
Rails.application.routes.draw do
  resources :artists, :books, :video_games, :movies, :reviews, :users, :sessions
  resources :likes, only: [:new, :create, :destroy]

  root to: 'pages#home', as: 'homepage'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  include Reviewables::InstanceMethods
  extend Reviewables::ClassMethods
  has_many :reviews, as: :reviewable
  validates :title, presence: true, uniqueness: true

end

app/models/book.rb
class Book < ApplicationRecord
  include Reviewables::InstanceMethods
  extend Reviewables::ClassMethods
  has_many :reviews, as: :reviewable
  has_many :likes, as: :likeable
  validates :title, presence: true, uniqueness: true
  validates :author, presence: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
  # validates :content, :rating, presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  include Reviewables::InstanceMethods
  extend Reviewables::ClassMethods
  has_many :reviews, as: :reviewable
  validates :title, presence: true, uniqueness: true
  validates :director, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :reviewable, polymorphic: true
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, less_than_or_equal_to: 5, greater_than_or_equal_to: 1 }
  validates :user_id, uniqueness: { scope: :reviewable, message: "You can only write one review" }
end

app/models/reviewables.rb
module Reviewables

  module InstanceMethods

    def average_rating
      if !reviews.empty?
        ratings = reviews.collect { |review| review.rating }
        (ratings.inject{ |sum, el| sum + el }.to_f / ratings.size).round(2)
      else
        "No reviews"
      end
    end

  end

  module ClassMethods

    def top_5
      array = self.all.collect do |instance|
        unless instance.average_rating == "No reviews"
          instance
        end
      end.compact

      array = array.sort_by do |instance|
        instance.average_rating
      end
      array.pop(5).reverse!
    end

  end



end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :reviewables, through: :reviews
  
  has_many :likes
  has_many :likeables, through: :likes
  has_secure_password

  validates :name, :email, :password_digest, :username, presence: true
  validates :email, :username, uniqueness: true
end

app/models/video_game.rb
class VideoGame < ApplicationRecord
  include Reviewables::InstanceMethods
  extend Reviewables::ClassMethods
  has_many :reviews, as: :reviewable
  validates :title, presence: true, uniqueness: true

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])

    if logged_in?
      @review = Review.find_or_initialize_by(reviewable_id: @book.id, user_id: current_user.id, reviewable_type: "Book")
    else
      @review = Review.find_by(reviewable_id: @book.id, reviewable_type: "Book")
    end

    if logged_in?
      @like = Like.find_or_initialize_by(likeable_id: @book.id, user_id: current_user.id, likeable_type: "Book")
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    unless @book.save
      render :new
    else
      flash[:notice] = "Book has been successfully created"
      redirect_to book_path(@book)
    end
  end
  private
  def book_params
    params.require(:book).permit(:title, :author)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def new
  end

  def create
    @like = Like.new(like_params)
    @like.user_id = current_user.id
    @like.save
    flash[:notice] = "Successfully added to your list!"
    redirect_to "/#{@like.likeable_type.underscore.pluralize}/#{@like.likeable_id}"
  end

  def destroy
    @like = Like.find(params[:id])
    path = "/#{@like.likeable_type.underscore.pluralize}/#{@like.likeable_id}"
    @like.destroy
    flash[:notice] = "Successfully removed from your list!"
    redirect_to path
  end

  private
  def like_params
    params.require(:like).permit(:likeable_type, :likeable_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_games_helper.rb
module VideoGamesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RatingsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="" role="navigation">
      <div class="nav-wrapper container">
        <ul>
          <li><%= link_to "Home", homepage_path %></li>
          <li><%= link_to "Books", books_path %></li>
          <li><%= link_to "Movies", movies_path %></li>
          <li><%= link_to "Video Games", video_games_path %></li>
          <li><%= link_to "Artists", artists_path %></li>
          <% if logged_in? %>
            <li class="right"><%= link_to "Logout", '/sessions/:id', method: 'delete' %></li>
            <li class="right"><%= link_to current_user.name, user_path(current_user) %></li>
          <% else %>
            <li class="right"><%= link_to "Sign Up", new_user_path %></li>
            <li class="right"><%= link_to "Log In", new_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if flash[:notice] %>
      <div class="card-panel teal lighten-2 flow-text center"><p><%= flash[:notice] %></p></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="index-banner">
  <br>
  <br>
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <%= image_tag "LISTED-LOGO.png" %>
      </div>
      <br>
      <br>
      <p class="row center">A platform for rating and reviewing books, movies, video games, and artists.</p>
        <p class="row center">Sign up or log in to leave your own ratings and reviews, or browse existing reviews created by other users.</p>

    </div>
  </div>
</div>


<!-- <% if !logged_in? %>
  <div class="row center login_signup">
    <%= link_to "Log In", new_session_path, class: "btn-large waves-effect waves-light teal lighten-1" %>
    <br/>
    <br/>
    <%= link_to "Sign Up", new_user_path, class: "btn-large waves-effect waves-light teal lighten-1" %>
  </div>
<% end %> -->

app/views/partials/_like_form.html.erb
<% unless liked?(@like) %>
  <%= form_for(@like) do |f| %>
    <%= f.hidden_field :likeable_id, :value => @like.likeable.id %>
    <%= f.hidden_field :likeable_type, :value => @like.likeable.class.to_s %>
    <%= f.submit "Add to my list", class: "btn waves-effect waves-light teal lighten-1" %>
  <% end %>
<% else %>
  <%= form_for(@like, method: "delete") do |f| %>
    <%= f.hidden_field :likeable_id, :value => @like.likeable.id %>
    <%= f.hidden_field :likeable_type, :value => @like.likeable.class.to_s %>
    <%= f.submit "Remove from my list", class: "btn waves-effect waves-light teal lighten-1" %>
  <% end %>
<% end %>

app/views/partials/_login_signup.html.erb
<p>You don't appear to be logged in</p>

<%= link_to "Log In", new_session_path, class: "btn waves-effect waves-light teal lighten-1" %>
<span> or </span>
<%= link_to "Sign Up", new_user_path, class: "btn waves-effect waves-light teal lighten-1" %>

app/views/partials/_review_form.html.erb
<h5>Your Review</h5>
  <%= form_for(@review) do |f| %>
    <div class="row">
      <%= f.label :content, class: "tiny input-field col s3"  %>
      <%= f.text_area :content, class: "input-field col s9", rows: "30" %>
    </div>
    <div class="row">
      <%= f.label :rating, class: "tiny input-field col s3" %>
      <%= f.number_field :rating, placeholder: '0-5', class: "input-field col s2" %>
    </div>
    <div class="row">
      <%= f.hidden_field :reviewable_id, :value => @review.reviewable.id %>
      <%= f.hidden_field :reviewable_type, :value => @review.reviewable.class.to_s %>
      <%= f.submit class:"btn waves-effect waves-light teal lighten-1" %>
    </div>
  <% end %>

app/views/partials/_review_list.html.erb
<h5>Reviews</h5>
<% if @review %>
<ul>
<% @review.reviewable.reviews.each do |review| %>
    <li class="row card">
      <div class="">
        <div class="row reviewable-row">
          <label class="tiny col s2">User: </label>

          <span class="tiny col s1"><%=link_to "#{review.user.username}", user_path(review.user_id) %></span>
        </div>

        <div class="row reviewable-row">
          <label class="tiny col s2">Rating: </label>
          <span class="tiny col s1"><%= review.rating %></span>
        </div>

        <div class="row reviewable-row">
          <label class="tiny col s1">Review: </label>
        </div>

        <div class="row">
          <span class="col s12"><%= review.content %></span>
        </div>

        <% if logged_in? && current_user.id == review.user_id %>
          <%= button_to("Delete Review", review_path(review), method: 'delete', class: "btn waves-effect waves-light teal lighten-1")%>
        <% end %>
      </div>
    </li>
<% end %>
</ul>

<% end %>